name: Update TFSA JSON
on:
  schedule:
    - cron: "0 13 * * *"    # every day at 13:00 UTC ~ 10am Halifax (+/- DST)
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip yfinance
      - run: python backend/tfsa_prices.py
      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/tfsa_portfolio.json
          git commit -m "Update TFSA portfolio JSON" || echo "No changes"
          git push
